create database MyWorkshipDB;
use MyWorkshipDB;


/*---------------LOGIN USUARIO--------------------------*/

create table `TB_USUARIO_CLIENTE`  (
	ID_USUARIO_CLIENTE	INT PRIMARY KEY AUTO_INCREMENT,                        
	NM_USUARIO      	VARCHAR(100),
	DS_CPF      		VARCHAR(100),
	DS_PAIS     		VARCHAR(50),
	DS_ESTADO  			VARCHAR(100),
	DS_CIDADE			VARCHAR(100)
);

create table `TB_LOGIN_CLIENTE`  (
	ID_LOGIN_CLIENTE    INT PRIMARY KEY AUTO_INCREMENT, 
    ID_USUARIO_CLIENTE  INT,
	DS_EMAIL            VARCHAR(100),
	DS_SENHA            VARCHAR(100),
    FOREIGN KEY (ID_USUARIO_CLIENTE) REFERENCES TB_USUARIO_CLIENTE (ID_USUARIO_CLIENTE)
);

create table `TB_PERFIL_CLIENTE`  (
	ID_PERFIL_CLIENTE    INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO_CLIENTE   INT,
	NM_PERFIL_EMPRESA    VARCHAR(100),
	IMG_PERFIL_CLIENTE   VARCHAR(500),
    FOREIGN KEY (ID_USUARIO_CLIENTE) REFERENCES TB_USUARIO_CLIENTE (ID_USUARIO_CLIENTE)
);

/*---------------LOGIN EMPRESA--------------------------*/

create table `TB_USUARIO_EMPRESA`  (
	ID_USUARIO_EMPRESA  			INT PRIMARY KEY AUTO_INCREMENT,           
	DS_CNPJ                         VARCHAR(10),
	DS_INSCRICAO_ESTADUAL           VARCHAR(100),
	NM_NOME_DA_EMPRESA              VARCHAR(100),
	DS_ESTADO                       VARCHAR(100),
	NM_REPRESENTANTE                VARCHAR(100),
	DS_CPF_REPRESENTANTE            VARCHAR(12),
	DS_CARGO_REPRESENTANTE          VARCHAR(100),
	DS_NACIONALIDADE_REPRESENTANTE  VARCHAR(100)
);

create table `TB_LOGIN_CLIENTE`  (
	ID_LOGIN_CLIENTE    INT PRIMARY KEY AUTO_INCREMENT, 
    ID_USUARIO_CLIENTE	INT,
	DS_EMAIL            VARCHAR(100),
	DS_SENHA            VARCHAR(100),
    FOREIGN KEY (ID_USUARIO_CLIENTE) REFERENCES TB_USUARIO_CLIENTE (ID_USUARIO_CLIENTE)
);

create table `TB_LOCAL_EMPRESA`  (
	ID_LOCAL_EMPRESA	INT PRIMARY KEY AUTO_INCREMENT, 
    ID_USUARIO_EMPRESA	INT,
    DS_PAIS             VARCHAR(100),
	DS_ESTADO           VARCHAR(100),
	DS_CIDADE           VARCHAR(100),
	DS_ENDERECO         VARCHAR(150),
	DS_CEP              VARCHAR(15),
    FOREIGN KEY (ID_USUARIO_EMPRESA) REFERENCES TB_USUARIO_EMPRESA (ID_USUARIO_EMPRESA)
);

/*---------------PAGINA EMPRESA--------------------------*/

create table `TB_PAGINA_EMPRESA`  (
	ID_PAGINA_EMPRESA   INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO_EMPRESA	INT,
	NM_EMPRESA          VARCHAR(100),
	IMG_LOGO            VARCHAR(200),
	DS_DESCRICAO        VARCHAR(100),
	FOREIGN KEY (ID_USUARIO_EMPRESA) REFERENCES TB_USUARIO_EMPRESA (ID_USUARIO_EMPRESA)
);

create table `TB_PAGINA_EMPRESA_PUBLICACAO`  (
	ID_PAGINA_EMPRESA_PUBLICACAO	INT PRIMARY KEY AUTO_INCREMENT, 
    ID_PAGINA_CLIENTE				INT,
	NM_TITULO                       VARCHAR(100),
	DS_CAIXA_TEXTO                  VARCHAR(1000),
    FOREIGN KEY (ID_PAGINA_CLIENTE) REFERENCES TB_PAGINA_CLIENTE (ID_PAGINA_CLIENTE)
);

create table `TB_PAGINA_EMPRESA_PUBLICACAO_IMG`  (
	ID_PAGINA_EMPRESA_PUBLICACAO_IMG	INT PRIMARY KEY AUTO_INCREMENT,
    ID_PAGINA_EMPRESA_PUBLICACAO		INT,
	IMG_IMAGEM_PUBLICACAO               VARCHAR(1000),
    FOREIGN KEY (ID_PAGINA_EMPRESA_PUBLICACAO) REFERENCES TB_PAGINA_EMPRESA_PUBLICACAO (ID_PAGINA_EMPRESA_PUBLICACAO)
);

create table `TB_TAG`  (
	ID_TAG	INT PRIMARY KEY AUTO_INCREMENT,
	NM_TAG  VARCHAR(100)
);

create table `TB_TAG_EMPRESA`  (
	ID_TAG				INT PRIMARY KEY AUTO_INCREMENT,
    ID_PAGINA_EMPRESA	INT,
    FOREIGN KEY (ID_TAG) REFERENCES TB_TAG (ID_TAG),
    FOREIGN KEY (ID_PAGINA_EMPRESA) REFERENCES TB_PAGINA_EMPRESA (ID_PAGINA_EMPRESA)
);

create table `TB_VERIFICACOES`  (
	ID_VERIFICACOES		INT PRIMARY KEY AUTO_INCREMENT,
    ID_PAGINA_EMPRESA	INT,
	DS_VERIFICACOES     VARCHAR(100),
    FOREIGN KEY (ID_PAGINA_EMPRESA) REFERENCES TB_PAGINA_EMPRESA (ID_PAGINA_EMPRESA)
);

create table `TB_CERTIFICACOES`  (
	ID_VERIFICACOES		INT PRIMARY KEY AUTO_INCREMENT,
    ID_PAGINA_EMPRESA	INT,
	DS_CERTIFICACOES     VARCHAR(100),
    FOREIGN KEY (ID_PAGINA_EMPRESA) REFERENCES TB_PAGINA_EMPRESA (ID_PAGINA_EMPRESA)
);

/*---------------AGENDAMENTO--------------------------*/

create table `TB_AGENDAMENTO`  (
	ID_AGENDAMENTO		INT PRIMARY KEY AUTO_INCREMENT,
	ID_USUARIO_EMPRESA  INT,
	ID_USUARIO_CLIENTE  INT,
	NM_PESSOA           VARCHAR(100),
	DS_EMAIL            VARCHAR(200),
	DS_CPF              VARCHAR(15),
	DS_TELEFONE         VARCHAR(10),
	DS_SEXO             VARCHAR(25),
	DT_NASCIMENTO       DATETIME,
	DS_DIA              INT,
	DS_LOCAL            VARCHAR(100),
	DS_HORA             VARCHAR(100),
    FOREIGN KEY (ID_USUARIO_EMPRESA) REFERENCES TB_USUARIO_EMPRESA (ID_USUARIO_EMPRESA),
    FOREIGN KEY (ID_USUARIO_CLIENTE) REFERENCES TB_USUARIO_CLIENTE (ID_USUARIO_CLIENTE)
);

create table `TB_AGENDAMENTO_CAMPO_TEXTO`  (
	ID_AGENDAMENTO		INT PRIMARY KEY AUTO_INCREMENT,
	ID_USUARIO_EMPRESA  INT,
	ID_USUARIO_CLIENTE  INT,
	NM_CAMPO_TEXTO      VARCHAR(100),
    DS_CAMPO_TEXTO      VARCHAR(1000),
    FOREIGN KEY (ID_USUARIO_EMPRESA) REFERENCES TB_USUARIO_EMPRESA (ID_USUARIO_EMPRESA),
    FOREIGN KEY (ID_USUARIO_CLIENTE) REFERENCES TB_USUARIO_CLIENTE (ID_USUARIO_CLIENTE)
);

create table `TB_EMPRESA_AVALIACAO`  (
	ID_EMPRESA_AVALIACAO	INT PRIMARY KEY AUTO_INCREMENT,
	ID_USUARIO_EMPRESA  	INT,
	ID_USUARIO_CLIENTE  	INT,
	VL_AVALIACAO       		DECIMAL(1,1),
	DS_AVALIACAO        	VARCHAR(500),
	DT_AVALIACAO        	DATETIME,
    FOREIGN KEY (ID_USUARIO_EMPRESA) REFERENCES TB_USUARIO_EMPRESA (ID_USUARIO_EMPRESA),
    FOREIGN KEY (ID_USUARIO_CLIENTE) REFERENCES TB_USUARIO_CLIENTE (ID_USUARIO_CLIENTE)
);

create table `TB_FAVORITO`  (
	ID_FAVORITO				INT PRIMARY KEY AUTO_INCREMENT,
	ID_USUARIO_EMPRESA  	INT,
	ID_USUARIO_CLIENTE  	INT,
	DS_FAVORITO				BOOL,
    FOREIGN KEY (ID_USUARIO_EMPRESA) REFERENCES TB_USUARIO_EMPRESA (ID_USUARIO_EMPRESA),
    FOREIGN KEY (ID_USUARIO_CLIENTE) REFERENCES TB_USUARIO_CLIENTE (ID_USUARIO_CLIENTE)
);
